vich_uploader:
    db_driver: orm

    mappings:
        upload_image:
            uri_prefix: /images/upload
            upload_destination: '%kernel.project_dir%/public/images/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        property_pdf:
            uri_prefix: /pdf/upload
            upload_destination: '%kernel.project_dir%/public/pdf/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        property_video:
            uri_prefix: /video/upload
            upload_destination: '%kernel.project_dir%/public/video/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer